// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.0--rc2
// source: proto_types/enums.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumDC int32

const (
	EnumDC_DcAS EnumDC = 0
	EnumDC_DcNA EnumDC = 8
	EnumDC_DcEu EnumDC = 16
)

// Enum value maps for EnumDC.
var (
	EnumDC_name = map[int32]string{
		0:  "DcAS",
		8:  "DcNA",
		16: "DcEu",
	}
	EnumDC_value = map[string]int32{
		"DcAS": 0,
		"DcNA": 8,
		"DcEu": 16,
	}
)

func (x EnumDC) Enum() *EnumDC {
	p := new(EnumDC)
	*p = x
	return p
}

func (x EnumDC) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumDC) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_enums_proto_enumTypes[0].Descriptor()
}

func (EnumDC) Type() protoreflect.EnumType {
	return &file_proto_types_enums_proto_enumTypes[0]
}

func (x EnumDC) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumDC.Descriptor instead.
func (EnumDC) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_enums_proto_rawDescGZIP(), []int{0}
}

var File_proto_types_enums_proto protoreflect.FileDescriptor

var file_proto_types_enums_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x2a, 0x26, 0x0a, 0x06, 0x45, 0x6e, 0x75, 0x6d, 0x44, 0x43, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x63,
	0x41, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x63, 0x4e, 0x41, 0x10, 0x08, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x63, 0x45, 0x75, 0x10, 0x10, 0x42, 0x18, 0x5a, 0x16, 0x4f, 0x63, 0x65, 0x61,
	0x6e, 0x49, 0x44, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_types_enums_proto_rawDescOnce sync.Once
	file_proto_types_enums_proto_rawDescData = file_proto_types_enums_proto_rawDesc
)

func file_proto_types_enums_proto_rawDescGZIP() []byte {
	file_proto_types_enums_proto_rawDescOnce.Do(func() {
		file_proto_types_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_types_enums_proto_rawDescData)
	})
	return file_proto_types_enums_proto_rawDescData
}

var file_proto_types_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_types_enums_proto_goTypes = []interface{}{
	(EnumDC)(0), // 0: Types.EnumDC
}
var file_proto_types_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_types_enums_proto_init() }
func file_proto_types_enums_proto_init() {
	if File_proto_types_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_types_enums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_enums_proto_goTypes,
		DependencyIndexes: file_proto_types_enums_proto_depIdxs,
		EnumInfos:         file_proto_types_enums_proto_enumTypes,
	}.Build()
	File_proto_types_enums_proto = out.File
	file_proto_types_enums_proto_rawDesc = nil
	file_proto_types_enums_proto_goTypes = nil
	file_proto_types_enums_proto_depIdxs = nil
}
